name: DEV

on:
  push:
    branches: [ "main" ] #replace with desired branch
  workflow_dispatch:
    inputs:
      logLevel:
      description: 'Log level'
      required: true
      type: boolean
  # pull_request:
  #   branches: [ "main" ]

jobs:
  Plugin-Build:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Package
      run: bash ./test.sh
      env:
        accountUsername: ${{ secrets.ACCOUNTUSERNAME }}
    
    - name: Build and Package
      run: mvn -f ./pom.xml clean package  #replace

    - name: Maven Test
      run: mvn -f ./pom.xml test #replace

    - name: Upload JAR Artifacts
      uses: actions/upload-artifact@v4.3.6
      with:
        name: Artifact-JAR
        path: target/*.jar  #replace


  Workflow-Packaging:
    needs: [Plugin-Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Prepare and Package Workflows
    #   working-directory: config
    #   run: bash render-workflows.sh <absolute path to DEV Property file.json> <Retailer Name> workflows/workflow1.json workflows/workflow2.json... #replace as required
    
    - name: Upload Workflow Files
      uses: actions/upload-artifact@v4.3.6
      with:
        name: Artifact-WorkflowFiles
        path: config/workflows/replaced/*.json  #replace as required


  # Settings-Packaging:
  #   needs: [Workflow-Packaging]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Package Settings
  #     working-directory: .
  #     run: ls

  #   - name: Upload Setting Files
  #     uses: actions/upload-artifact@v4.3.6
  #     with:
  #       name: Artifact-SettingFiles
  #       path: config/workflows/replaced/*.json #replace


  # Manifest-Packaging:
  #   needs: [Settings-Packaging]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Package Manifest
  #     working-directory: .
  #     run: ls

  #   - name: Upload Manifest File
  #     uses: actions/upload-artifact@v4.3.6
  #     with:
  #       name: Artifact-ManifestFiles
  #       path: config/workflows/replaced/*.json #replace

  Deploy:
    runs-on: ubuntu-latest
    needs: [Plugin-Build, Workflow-Packaging] #, Settings-Packaging, Manifest-Packaging]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4

    - name: Deploy Plugin
      run: bash deploy.sh      
      
  # publish-job:
  #   runs-on: ubuntu-latest
  #   needs: build_test
    # steps:
    # - uses: actions/checkout@v3
    # - uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    # - run: mvn --batch-mode --update-snapshots verify
    # - run: mkdir staging && cp target/*.jar staging
    # # - uses: actions/upload-artifact@v3
    #   with:
    #     name: Package
    #     path: staging
